# Generated by Django 6.0.7 on 2026-07-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='cover')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
